### PR TITLE
Fix missed geometry change events

### LINKED ISSUE #135: Adding/removing a desktop breaks layouts on all desktops
A picture is worth a thousand words...

Initial state:
Screenshot_20190327_132519

Desktop added:
Screenshot_20190327_132555

### PR DESCRIPTION
**Pull request by laloch**
KWin sometimes decides to update geometry of several/all clients simultaneously. Our timer-based asynchronous handler needs to be ready for that. It also needs to handle geometry changes happening
to clients outside of the current desktop, because some effects such as Desktop Grid display badly damaged layouts if it doesn't.

Fixes #135

### CODE REVIEW

**Comment by faho** [comment]
>KWin sometimes decides to update geometry of several/all clients simultaneously

Why though?

We're adding a desktop. Why are clients on other desktops now updating? Is there maybe something we should ignore instead?

-----

The code is probably correct regardless - what happens if a client resizes in the interval otherwise, for any other reason? - but I'd like to understand what's happening here.

**Comment by laloch** [comment]
> Why though?

I'd also like to know. Maybe I'll try to investigate a bit. This seems to me like a potential bug in KWin.

> what happens if a client resizes in the interval otherwise, for any other reason?

I thought about it. Yes, we would have a problem, but frankly, I failed to find a legitimate scenario in which a client would be updating its geometry in <1ms intervals.

**Comment by faho** [comment]
>I failed to find a legitimate scenario in which a client would be updating its geometry in <1ms intervals.

A client can resize any time, for every reason. E.g. vlc can be configured to resize according to video resolution. Or a new client can appear.

File: contents/code/tile.js [hunk 1]
```diff
@@ -202,12 +202,6 @@ Tile.prototype.setClientGeometry = function(client) {
             print("Wrong tile called");
             return;
         }
-        // Don't resize when we aren't the current desktop
-        // or on all desktops
-        if (this._currentDesktop != workspace.currentDesktop
-            && this._currentDesktop != -1) {
-            return;
-        }
```
Comment (faho) [inline contents/code/tile.js]: What's the rationale for removing this?

It should still work. The idea is that we restore the geometry when we switch desktops, so changes to a desktop while it's in the background don't affect the tiling and we can ignore a bunch of work.

Or is there a problem with that?

Comment (laloch) [reply contents/code/tile.js]: Yep, as I wrote in the commit message, Desktop Grid effect displays damaged layouts if we don't keep them maintained all the time.

Comment (faho) [reply contents/code/tile.js]: Urgh, yeah, sorry, missed that!

**Comment by faho** [comment]
Okay, so let's merge this now. Even if it turns out to be a KWin bug, we'd still have to work around it for a while since stable distributions are a thing.

**Comment by laloch** [comment]
Thanks for the review.

**Comment by laloch** [comment]
> A client can resize any time, for every reason. E.g. vlc can be configured to resize according to video resolution. Or a new client can appear.

Yes, that's why I maintain a FIFO with the events. As long as it does not happen in <1ms intervals _constantly_, it doesn't do any harm.
