### PR TITLE
Better shortcut defaults

### LINKED ISSUE #141: Problematic default key bindings
We have some conflicting default key bindings:

Next tiling layout - <kbd>Meta</kbd> + <kbd>PgUp</kbd> is used by KWin for "Maximize Window".
Previous tiling layout - <kbd>Meta</kbd> + <kbd>PgDown</kbd> is used by KWin for "Minimize Window".

Then we have some default shortcuts that do not work on standard US keyboard layout:

Swap with next tile - <kbd>Meta</kbd> + <kbd>Shift</kbd> + <kbd>[</kbd> - there is no such key. It's <kbd>Meta</kbd> + <kbd>{</kbd>.
Swap with previous tile - <kbd>Meta</kbd> + <kbd>Shift</kbd> + <kbd>]</kbd> - there is no such key. It's <kbd>Meta</kbd> + <kbd>}</kbd>.

### PR DESCRIPTION
**Pull request by faho**
Fixes #141.

Switch the default shortcuts for prev/next layout to meta+*shift*+pgdown/up.

Remove the defaults for some more advanced bindings, so users that want to use them can set them themselves.

### CODE REVIEW

File: contents/code/tilingmanager.js [hunk 1]
```diff
@@ -447,7 +447,7 @@ function TilingManager(timer) {
                               });
         KWin.registerShortcut("TILING: Focus next tile",
                               "Focus next tile",
-                              "Meta+]",
+                              "",
```
Comment (laloch) [inline contents/code/tilingmanager.js]: Are you sure about this one and the next? It might be just about my workflow, but I consider them to be quite essential.

Comment (faho) [reply contents/code/tilingmanager.js]: KWin already has shortcuts to select the window above/below/to the right/left.

These are only really of use if you care about the tile *order* in a numeric sense.
